#define GPIO_RELAY GPIO_NUM_2
#define RELAY_ACTIVE_LEVEL 1

#define GPIO_BUTTON_UP_PIN GPIO_NUM_4
#define GPIO_BUTTON_DOWN_PIN GPIO_NUM_5

#define HLK_PRESENCE_PIN    GPIO_NUM_13

#define HLK_UART_PORT       UART_NUM_2
#define UART_BAUD_RATE      115200
#define HLK_UART_TXD        GPIO_NUM_17
#define HLK_UART_RXD        GPIO_NUM_35
#define UART_BUF_SIZE       1024
#define LINE_BUF_SIZE       256

#define GPIO_SDA GPIO_NUM_21
#define GPIO_SCL GPIO_NUM_22

#define THERMISTOR_ENVIRONMENT ADC_CHANNEL_6
#define THERMISTOR_RADIATOR ADC_CHANNEL_7

#define SENSOR_MIN_VALID_TEMP (-40.0f)
#define SENSOR_MAX_VALID_TEMP (80.0f)
#define MAX_TEMP_JUMP_PER_SEC (5.0f)